### PR TITLE
Artifacthub changelog check

### PR DESCRIPTION
**Pull request by smlx**
Add a CI check that the artifacthub changelog has been updated.

### CODE REVIEW

**Comment by smlx** [comment]
I added two commits to show the new CI check working: The first updates the chart version without updating the changelog and fails. The second updates the changelog and passes.

Once approved I'll remove those test commits before merging.

**Comment by tobybellwood** [comment]
Great I can see the fail at https://github.com/uselagoon/lagoon-charts/actions/runs/3637210163/jobs/6137975721 - works well!

We should roll this to all the charts on artifacthub - core, remote, logging, logs-concentrator and build-deploy.

**Comment by smlx** [comment]
This action checks all the charts, lagoon-logging was just a demo.

**Review by tobybellwood — APPROVED** [review]
LGTM - works as designed!

**Pull request merged**
