### PR TITLE
Add ssh-portal and ssh-portal-api

### PR DESCRIPTION
**Pull request by smlx**
# Description

This PR makes some fairly substantial changes to the `lagoon-core` and `lagoon-remote` charts, but the new stuff is disabled by default, so unless you opt-in there shouldn't be any significant change to existing installations.
The new features are enabled in CI for testing purposes.

It adds:

* NATS in `lagoon-core`.
* NATS in `lagoon-remote`.
* Authorization and authentication config for `ssh-portal` and `service-api` NATS clients.
* Documentation around how to protect NATS with TLS.
* SSH Portal API in `lagoon-core`.
* SSH Portal in `lagoon-remote`.
* Environment variables to support the new ssh-portal test suite in `lagoon-test`.

The Lagoon PR https://github.com/uselagoon/lagoon/pull/2941 makes changes in support of this PR.
The ssh-portal / ssh-portal-api repository is here: https://github.com/uselagoon/lagoon-ssh-portal

NOTE: This design uses NATS to provide authentication, authorization and TLS between remote/core. However the NATS backend _could_ be swapped out for RabbitMQ if necessary. The current experimental implementation of `ssh-portal`/`ssh-portal-api` does not implement RabbitMQ support but this could be added.

### CODE REVIEW

**Comment by smlx** [comment]
I removed some manual image repository/tag config, but I still need to set the image registry/tag to `testlagoon`/`main` in the `Makefile` in order to pull in the `tests` image with the `ssh-portal` tests.

**Comment by smlx** [comment]
Ok, I think this is ready for review.

**Comment by smlx** [comment]
OK, this is really ready for review now. I ran the `ssh-portal` test suite in a loop overnight with no failures so pretty confident that the race condition with NATS is fixed.

**Comment by shreddedbacon** [comment]
@smlx are you still working on this actively?

**Comment by smlx** [comment]
Yes, I'm rebasing and getting it running with upstream Lagoon main again.

**Review by shreddedbacon — COMMENTED** [review]
I fired this up locally and played with this, this is great!

I'm still not 100% sure about how to do the certificate generation for the NATS cluster though if this were to be done with a public CA. The notes say to create a certificate, but can't use HTTP-01 solver, so how does it get the cert?

**Comment by smlx** [comment]
Right now I'm assuming generation of a private certificate similar to the `lagoon-logging` chart. See these instructions: https://github.com/uselagoon/lagoon-charts/pull/382/files#diff-a9549b9b7e24122365a4aa305b82ba8c55714d55a0180dc30048185befcbbd2aR222-R244

That's where the certs used in CI come from.

A public CA would simplify configuration a bit but it's not currently possible without a DNS01 certificate issuer.

**Comment by shreddedbacon** [comment]
Cool, well I'm good with this. Locally alone SSH is faster, so should definitely be faster once it rolls out properly.

**Comment by smlx** [comment]
Ok, rebased and (assuming tests go green!) ready for review again @tobybellwood

**Comment by smlx** [comment]
Rebased again to fix the conflict.

**Comment by shreddedbacon** [comment]
Sorry I'm messing all your stuff up here :(

**Review by tobybellwood — APPROVED** [review]
Happy to merge this - it's all disabled for now, and add a note that we recommend leaving it disabled until the services are ready

**Pull request merged**
