### PR TITLE
Remove install-tests target from Makefile

### PR DESCRIPTION
**Pull request by smlx**
The install-tests target was installing the lagoon-test chart manually, which breaks assumptions in the helm chart-testing tooling and also breaks `kind/retest` in the `uselagoon/lagoon` Makefile.

So remove that target and instead update the fill-test-ci-values target to do the thing that install-tests was intended to do.

### CODE REVIEW

**Comment by smlx** [comment]
I've got an associated PR in the works for the Lagoon Makefile and docs.

**Comment by tobybellwood** [comment]
Maybe the `install-tests` routine name should be preserved to bundle `fill-test-ci-values` and it's pre-reqs (install-ingress install-lagoon-core install-lagoon-remote install-nfs-server-provisioner) rather than have the fill-test-ci-values performing dual tasks based on a var - IMO it makes sense to just use it to fill values?  We'd obvs have to change a couple other actions tho?

**Comment by smlx** [comment]
The thing is that in order to fill the template values those charts _do_ actually have to be installed, so IMO it makes sense to declare the dependencies. It's just that the special case of `kind/retest` in the Lagoon Makefile is reusing the existing cluster.

This complexity is all hidden from the user of the Makefile so I though it made sense to keep the logic for templating the yaml in one place?

I'll send some PRs to Lagoon shortly with some associated documentation and other tweaks to the Makefile that might help show where I'm going with this. Happy for you to rework this if you like of course :slightly_smiling_face:

**Comment by tobybellwood** [comment]
I'm still happy, just wanted to check - I just always thought it strange that a fill-test-ci-values command was used to deploy an entire Lagoon!

**Review by tobybellwood — APPROVED** [review]
I'm happy - it'll be better for getting the retest logic smarter!

**Pull request merged**
