### PR TITLE
Additional core services port forwarding

### PR DESCRIPTION
**Pull request by timclifford**
Some additional Makefile port-forwarding support

### CODE REVIEW

**Comment by timclifford** [comment]
I've left the new ones off the main port-forward task, but now can be added to for easier development https://github.com/uselagoon/lagoon-charts/pull/384/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L348

**Review by tobybellwood — APPROVED** [review]
Lgtm given that they can be changed easily if clashing

**Comment by smlx** [comment]
@tobybellwood if approved could we merge this?

**Comment by tobybellwood** [comment]
yes, it makes sense

**Pull request merged**
